import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import { MantineProvider } from '@mantine/core';
import { theme } from '@/lib/mantine/theme';
import QueryClientProviderWrapper from './_components/QueryClientProviderWrapper';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="ko">
        <body>
          <QueryClientProviderWrapper>
            <MantineProvider theme={theme}>{children}</MantineProvider>
          </QueryClientProviderWrapper>
        </body>
      </html>
    </SessionProvider>
  );
}
