name: Semgrep
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/default'
          github_token: ${{ secrets.GITHUB_TOKEN }}
